version: '3.8'

services:
  mssql2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql2022
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    volumes:
      - ./mssql_data:/var/opt/mssql

volumes:
  mssql_data:
