/*
==============================================
檔案名稱: sdb0country.sql
所屬模組: 生產
用途: 國家主檔
預存程序：無         
建立日期: 2025-04-13
建立者: 楊清雲（@eddie）
適用環境: 共用模組
==============================================
*/

CREATE TABLE [dbo].[sdb0country] (
    country_id      UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
    iso_code        VARCHAR(3)        NOT NULL UNIQUE, -- ISO 二碼
    iso3_code       VARCHAR(3)        NOT NULL,         -- ISO 三碼
    country_name_zh NVARCHAR(50)      NOT NULL,          -- 國家中文名稱
    country_name_en VARCHAR(100)      NOT NULL,          -- 國家英文名稱
    phone_code      VARCHAR(10)       NULL,              -- 國際電話碼
    currency_code   VARCHAR(3)        NULL,              -- 幣別代碼
    is_active       BIT               NOT NULL DEFAULT 1,-- 是否啟用
    created_at      DATETIME2         NOT NULL DEFAULT SYSUTCDATETIME(), -- 建立時間
    created_by      VARCHAR(50)       NULL,              -- 建立者
    updated_at      DATETIME2         NULL,              -- 更新時間
    updated_by      VARCHAR(50)       NULL               -- 更新者
);

-- 表註解
EXEC sys.sp_addextendedproperty 
@name = N'MS_Description', 
@value = N'國家主檔', 
@level0type = N'SCHEMA', @level0name = 'dbo',
@level1type = N'TABLE',  @level1name = 'sdb0country';

-- 欄位註解
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'國家主鍵（GUID）',             @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'sdb0country', @level2type=N'COLUMN', @level2name=N'country_id';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ISO 3166-1 二碼',               @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'sdb0country', @level2type=N'COLUMN', @level2name=N'iso_code';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ISO 3166-1 三碼',               @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'sdb0country', @level2type=N'COLUMN', @level2name=N'iso3_code';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'國家中文名稱',                  @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'sdb0country', @level2type=N'COLUMN', @level2name=N'country_name_zh';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'國家英文名稱',                  @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'sdb0country', @level2type=N'COLUMN', @level2name=N'country_name_en';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'國際電話碼',                    @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'sdb0country', @level2type=N'COLUMN', @level2name=N'phone_code';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'幣別代碼（如 TWD、USD）',         @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'sdb0country', @level2type=N'COLUMN', @level2name=N'currency_code';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'是否啟用（1=是，0=否）',           @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'sdb0country', @level2type=N'COLUMN', @level2name=N'is_active';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'建立時間（UTC）',                @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'sdb0country', @level2type=N'COLUMN', @level2name=N'created_at';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'建立者（帳號或系統）',            @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'sdb0country', @level2type=N'COLUMN', @level2name=N'created_by';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'最後更新時間',                   @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'sdb0country', @level2type=N'COLUMN', @level2name=N'updated_at';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'最後更新者',                     @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'sdb0country', @level2type=N'COLUMN', @level2name=N'updated_by';


INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('662d9c16-6f4c-459f-874d-f44e0265e7d9', 'AW', 'ABW', N'', 'Aruba', '', 'AWG', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('afa877af-4e2d-4477-a7e8-488819d35db4', 'AF', 'AFG', N'', 'Afghanistan', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('3c829031-d486-4971-b48e-c15972954532', 'AO', 'AGO', N'', 'Angola', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('7c636c36-ee56-4a21-9871-4fce8f5272d9', 'AI', 'AIA', N'', 'Anguilla', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('7fe24d22-edb2-4c8e-b555-1ce717821aa8', 'AX', 'ALA', N'', 'Åland Islands', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('242de926-fce1-4caa-9ecb-0b9c86c72924', 'AL', 'ALB', N'', 'Albania', '', 'ALL', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('b8c0e431-7e24-42af-82bf-ccbdcf99c784', 'AD', 'AND', N'', 'Andorra', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('ba755fc2-7ddc-4129-8bad-bf93b5a25a42', 'AE', 'ARE', N'', 'United Arab Emirates', '', 'AED', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('5a759592-2cc2-4924-beec-888f9f4b9d12', 'AR', 'ARG', N'', 'Argentina', '', 'ARS', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('ca5c2832-1f59-4fce-9045-4b6f89f579b0', 'AM', 'ARM', N'', 'Armenia', '', 'AMD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('20db3efd-e5d5-4732-9ba8-2f9fc37d4ec1', 'AS', 'ASM', N'', 'American Samoa', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('b6d95f72-299a-4da2-847a-e260de43f950', 'AQ', 'ATA', N'', 'Antarctica', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('2d5d4038-bed2-429b-904a-6db5006d9623', 'TF', 'ATF', N'', 'French Southern Territories', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('07f9b7ad-7453-4bbe-99e2-152ab346be02', 'AG', 'ATG', N'', 'Antigua and Barbuda', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('f7e0b23c-4cb6-4a75-8965-071c7d4174d2', 'AU', 'AUS', N'', 'Australia', '', 'AUD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('c08ae40c-e978-445e-bc43-3d317b64fa9e', 'AT', 'AUT', N'', 'Austria', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('a2f1db8c-b362-4b62-801c-89107e19e776', 'AZ', 'AZE', N'', 'Azerbaijan', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('b0d7d54b-0eb4-4cb3-b2ac-1d104d6914cc', 'BI', 'BDI', N'', 'Burundi', '', 'BIF', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('a23de3aa-2732-4c61-891b-e61e2660376f', 'BE', 'BEL', N'', 'Belgium', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('8fc4880d-4fa9-443f-83ec-ad368d7687f1', 'BJ', 'BEN', N'', 'Benin', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('1d10ab5c-181e-43ad-94f2-9d225ac71de9', 'BQ', 'BES', N'', 'Bonaire, Sint Eustatius and Saba', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('626ad958-9a41-4cb3-ae27-123cf89f7775', 'BF', 'BFA', N'', 'Burkina Faso', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('20020908-dbb3-4939-9cf7-be14b13c7c71', 'BD', 'BGD', N'', 'Bangladesh', '', 'BDT', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('f4a34e6e-b1dd-43d9-9166-ae4755193723', 'BG', 'BGR', N'', 'Bulgaria', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('c1861e18-392f-4d72-96e3-f9ad04feed19', 'BH', 'BHR', N'', 'Bahrain', '', 'BHD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('131ef2c2-41af-4da5-9cd6-c48a1836ac67', 'BS', 'BHS', N'', 'Bahamas', '', 'BSD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('54488d31-a82f-4894-af7b-545fe7721a2b', 'BA', 'BIH', N'', 'Bosnia and Herzegovina', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('a7e615a0-4ba4-44c4-9122-f42bce99ad98', 'BL', 'BLM', N'', 'Saint Barthélemy', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('b5e343c5-b5af-4d8e-b8c1-8a866eec31b9', 'BY', 'BLR', N'', 'Belarus', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('8aff02c0-e40d-4ae1-8efa-3f7dd561c586', 'BZ', 'BLZ', N'', 'Belize', '', 'BZD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('1b49c181-1d0d-4c22-8ad0-3c5b8d767983', 'BM', 'BMU', N'', 'Bermuda', '', 'BMD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('05627ec6-8182-487e-be11-4d0d30a779d5', 'BO', 'BOL', N'', 'Bolivia, Plurinational State of', '', 'BOB', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('98a31a9d-6655-4963-badc-997b22bd9c92', 'BR', 'BRA', N'', 'Brazil', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('5ecd9978-8155-4966-b6a8-68e183020e75', 'BB', 'BRB', N'', 'Barbados', '', 'BBD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('7cf7d849-2d10-49e1-84cf-889b15423b01', 'BN', 'BRN', N'', 'Brunei Darussalam', '', 'BND', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('86d862e2-7637-467e-91f9-1f96b5e15102', 'BT', 'BTN', N'', 'Bhutan', '', 'BTN', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('d98ccee3-f02f-4294-a3fd-c6f0417965a7', 'BV', 'BVT', N'', 'Bouvet Island', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('e87e0ac3-c7a6-42ec-a50d-8733f761da3d', 'BW', 'BWA', N'', 'Botswana', '', 'BWP', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('7c16094d-ee02-4d76-97d1-e0ca100e65d3', 'CF', 'CAF', N'', 'Central African Republic', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('145bdbd8-aed6-4547-a975-7f1d8de57130', 'CA', 'CAN', N'', 'Canada', '', 'CAD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('a34cac74-b6ee-4e3e-a9bc-92c45d2c5519', 'CC', 'CCK', N'', 'Cocos (Keeling) Islands', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('c6592a38-17f5-4734-8538-642c522b41e9', 'CH', 'CHE', N'', 'Switzerland', '', 'CHF', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('186fb4d0-dca0-4182-a707-0ccf90a17e1e', 'CL', 'CHL', N'', 'Chile', '', 'CLP', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('72297662-c54f-4a4f-8d59-14860e135b8c', 'CN', 'CHN', N'', 'China', '+86', 'CNY', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('60c33582-e21d-4d25-ba81-a2052e29989e', 'CI', 'CIV', N'', 'Côte d''Ivoire', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('82b595f2-d397-42fe-8e0a-bc397038883b', 'CM', 'CMR', N'', 'Cameroon', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('b33df75a-e334-4c5b-b962-89124b7b344a', 'CD', 'COD', N'', 'Congo, The Democratic Republic of the', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('edff9b35-4808-4bc2-8aa2-b017ecf6e7ee', 'CG', 'COG', N'', 'Congo', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('926ce48e-9080-4d9f-98de-954e3123678f', 'CK', 'COK', N'', 'Cook Islands', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('112f581a-b14e-4525-8ffc-610d5d00527a', 'CO', 'COL', N'', 'Colombia', '', 'COP', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('fb0dbde5-1248-4210-b202-0e179e51fb49', 'KM', 'COM', N'', 'Comoros', '', 'KMF', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('1f9e3d43-9d78-4302-a96e-865d077c251f', 'CV', 'CPV', N'', 'Cabo Verde', '', 'CVE', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('60d70cda-a616-4fbe-900a-61381def1fa8', 'CR', 'CRI', N'', 'Costa Rica', '', 'CRC', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('e353fc39-22cd-466c-88c1-5fae395c7672', 'CU', 'CUB', N'', 'Cuba', '', 'CUP', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('03aa1015-9fd5-4d70-943e-7bb40692e21c', 'CW', 'CUW', N'', 'Curaçao', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('0d550529-82e1-4265-a470-756da1175265', 'CX', 'CXR', N'', 'Christmas Island', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('f936309a-bfb8-4333-8596-38937e6cad3b', 'KY', 'CYM', N'', 'Cayman Islands', '', 'KYD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('0b3b3a22-b154-4796-8c46-dd311b1d2993', 'CY', 'CYP', N'', 'Cyprus', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('4b2f43da-ac9f-4fa1-9982-7f60a1306c10', 'CZ', 'CZE', N'', 'Czechia', '', 'CZK', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('3126f08f-1053-4e1e-8a01-0423a2f81e53', 'DE', 'DEU', N'', 'Germany', '+49', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('de6a3297-2fde-4f66-81a5-08e69dd43ea6', 'DJ', 'DJI', N'', 'Djibouti', '', 'DJF', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('098f5791-34d7-4f38-bef9-e165f344575b', 'DM', 'DMA', N'', 'Dominica', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('01c8588c-c016-45a1-8574-e9dc976f8cfe', 'DK', 'DNK', N'', 'Denmark', '', 'DKK', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('535ae716-f633-4094-9250-dc2818f10706', 'DO', 'DOM', N'', 'Dominican Republic', '', 'DOP', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('cfa075b6-094f-489b-bee3-22a824eaf69a', 'DZ', 'DZA', N'', 'Algeria', '', 'DZD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('5c89acec-5459-4299-9d55-9f06b72b280a', 'EC', 'ECU', N'', 'Ecuador', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('f81da5c6-f922-424c-ada0-472608f0d9b9', 'EG', 'EGY', N'', 'Egypt', '', 'EGP', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('187a8a89-3302-4560-afa1-15c1b56c210b', 'ER', 'ERI', N'', 'Eritrea', '', 'ERN', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('eaeb21d4-f904-45de-917b-8022bb5a0820', 'EH', 'ESH', N'', 'Western Sahara', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('efc92ef6-8f4e-4cbf-85ff-64c75ef87a57', 'ES', 'ESP', N'', 'Spain', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('edd7ca1f-4585-4b6f-89dc-d5c9383f52ba', 'EE', 'EST', N'', 'Estonia', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('a47ea080-664c-4f1d-b85e-f63eb45e69bf', 'ET', 'ETH', N'', 'Ethiopia', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('664c579d-9fb8-4334-8848-50b89338efc0', 'FI', 'FIN', N'', 'Finland', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('c5151b78-e2f3-4558-85f1-85d099c2d6bf', 'FJ', 'FJI', N'', 'Fiji', '', 'FJD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('285f8851-8ea2-44ae-853c-1fe50d34186b', 'FK', 'FLK', N'', 'Falkland Islands (Malvinas)', '', 'FKP', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('153c9c07-33b9-41f6-805d-d69d297c062b', 'FR', 'FRA', N'', 'France', '+33', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('fff234df-8b86-4ed1-b0b9-4b5e4c7fcb89', 'FO', 'FRO', N'', 'Faroe Islands', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('e1613cf9-0d15-4726-a4cd-1531134bd7c2', 'FM', 'FSM', N'', 'Micronesia, Federated States of', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('355c3437-efad-4172-82dd-e73f23e66ff8', 'GA', 'GAB', N'', 'Gabon', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('7161fd0c-9632-4515-936e-29bea3c5e488', 'GB', 'GBR', N'', 'United Kingdom', '+44', 'GBP', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('1c5f73ef-9459-4d31-a52b-69911a627165', 'GE', 'GEO', N'', 'Georgia', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('e5f7883f-7f64-4dbb-bc0f-c890778ea798', 'GG', 'GGY', N'', 'Guernsey', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('bc01aa5c-06ae-49be-bdd1-ff949ef8f447', 'GH', 'GHA', N'', 'Ghana', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('97fb5aa1-86ab-4d1a-abda-27345e0b1873', 'GI', 'GIB', N'', 'Gibraltar', '', 'GIP', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('d6b3440d-8fae-41f0-9f96-dd42bccea22d', 'GN', 'GIN', N'', 'Guinea', '', 'GNF', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('ce551e9b-d411-4dad-8a68-4de022a89ec9', 'GP', 'GLP', N'', 'Guadeloupe', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('5bbff45b-a907-4c0e-8865-660c549c6b64', 'GM', 'GMB', N'', 'Gambia', '', 'GMD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('27b1c07a-95b5-4b0d-a013-ca3aa10a0966', 'GW', 'GNB', N'', 'Guinea-Bissau', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('0dd9b5fa-8cd7-4ce0-a655-62fc76d634a1', 'GQ', 'GNQ', N'', 'Equatorial Guinea', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('0cbf9253-d027-4cd3-b9be-3f86026ba4ca', 'GR', 'GRC', N'', 'Greece', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('b0305b98-854f-4913-a20b-915578e1927f', 'GD', 'GRD', N'', 'Grenada', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('979e5b7c-2284-4e32-b801-1170e1bee37f', 'GL', 'GRL', N'', 'Greenland', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('34cb68ea-0cbc-46b7-8d31-0223b86635e8', 'GT', 'GTM', N'', 'Guatemala', '', 'GTQ', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('0d176261-e1c8-4f2e-87c1-9fd28af884f8', 'GF', 'GUF', N'', 'French Guiana', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('c38f156b-ef26-4c68-a439-8ff703e7f156', 'GU', 'GUM', N'', 'Guam', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('7b14ca95-3b02-4321-ab68-c7e44d4c37c1', 'GY', 'GUY', N'', 'Guyana', '', 'GYD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('299813c4-19b8-457c-9ee7-30951309ef68', 'HK', 'HKG', N'', 'Hong Kong', '', 'HKD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('5911f7dc-d4b2-4cec-9386-1fadd19e7744', 'HM', 'HMD', N'', 'Heard Island and McDonald Islands', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('9d0129a4-9108-4817-9d4c-6c5acbed4e42', 'HN', 'HND', N'', 'Honduras', '', 'HNL', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('2642609f-e93a-45e8-b467-9c8af1753bc5', 'HR', 'HRV', N'', 'Croatia', '', 'HRK', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('35debaa1-7ea1-4e29-a3f3-37375712d9c6', 'HT', 'HTI', N'', 'Haiti', '', 'HTG', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('e46eddb7-6264-4308-8f11-9375bcb84c7a', 'HU', 'HUN', N'', 'Hungary', '', 'HUF', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('567e6d83-6577-4e47-aa00-4060de48c4bb', 'ID', 'IDN', N'', 'Indonesia', '', 'IDR', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('d7a889e9-5926-46c4-8fa1-1e79be35a0c1', 'IM', 'IMN', N'', 'Isle of Man', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('071b657f-879b-4fc0-8a23-9f69bf24c9a4', 'IN', 'IND', N'', 'India', '', 'INR', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('746ae0dd-d256-44e0-8275-664f0efb8594', 'IO', 'IOT', N'', 'British Indian Ocean Territory', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('e4fbc379-2206-44e2-abb6-418cf6201c5f', 'IE', 'IRL', N'', 'Ireland', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('829b112c-eb92-4eb9-8b47-7d8182dfd4ea', 'IR', 'IRN', N'', 'Iran, Islamic Republic of', '', 'IRR', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('76692452-4091-47f2-bf87-dcba594a31e3', 'IQ', 'IRQ', N'', 'Iraq', '', 'IQD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('60b8a390-1940-4c17-a617-fca78f3d4016', 'IS', 'ISL', N'', 'Iceland', '', 'ISK', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('088ef012-4177-4035-9690-4e62b487f046', 'IL', 'ISR', N'', 'Israel', '', 'ILS', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('5fb0eba5-55e8-47e6-a715-2e4ed5a63610', 'IT', 'ITA', N'', 'Italy', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('d96d8a6c-af06-497a-bbc2-1fbf2116931a', 'JM', 'JAM', N'', 'Jamaica', '', 'JMD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('613bef3e-dae3-4713-a261-3dba1d670bd3', 'JE', 'JEY', N'', 'Jersey', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('1480bb7a-7753-4540-be38-7d695e2e2ef9', 'JO', 'JOR', N'', 'Jordan', '', 'JOD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('a313c379-d0c0-4ba4-9eb8-0359fe40d86e', 'JP', 'JPN', N'', 'Japan', '+81', 'JPY', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('7d2862c2-a0aa-4d30-927e-bf3875aa9d14', 'KZ', 'KAZ', N'', 'Kazakhstan', '', 'KZT', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('16432ade-c629-44fb-8c9c-968f440ea351', 'KE', 'KEN', N'', 'Kenya', '', 'KES', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('6d274072-0f4f-4fa5-ad17-bce17f37b7a3', 'KG', 'KGZ', N'', 'Kyrgyzstan', '', 'KGS', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('7895b194-8bc1-48b7-a28a-468d06e32652', 'KH', 'KHM', N'', 'Cambodia', '', 'KHR', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('4ab67632-50b6-4c9c-94bc-ea7ebaa9c648', 'KI', 'KIR', N'', 'Kiribati', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('60b57ff5-751d-45ae-bb88-459c0820ba47', 'KN', 'KNA', N'', 'Saint Kitts and Nevis', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('e3a5154a-b9ee-4b66-bdfc-4e7452f881e9', 'KR', 'KOR', N'', 'Korea, Republic of', '+82', 'KRW', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('a4250860-6fd7-496f-93ca-7caff6835808', 'KW', 'KWT', N'', 'Kuwait', '', 'KWD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('80fd2acd-1037-4da7-971f-261f2017592f', 'LA', 'LAO', N'', 'Lao People''s Democratic Republic', '', 'LAK', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('8182f379-f92f-4033-81f9-cf5f4b32c9cd', 'LB', 'LBN', N'', 'Lebanon', '', 'LBP', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('06b2b3e2-9f69-48eb-8f42-fae7a06adadf', 'LR', 'LBR', N'', 'Liberia', '', 'LRD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('6ad9c9f5-eb30-4ef6-9b19-1fc72532f95a', 'LY', 'LBY', N'', 'Libya', '', 'LYD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('80026970-efc5-4126-beeb-e4d368fec580', 'LC', 'LCA', N'', 'Saint Lucia', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('033793bf-580a-4abb-ac50-1f88d17a215d', 'LI', 'LIE', N'', 'Liechtenstein', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('598d5603-ab66-4b45-ba35-252d043e0c5a', 'LK', 'LKA', N'', 'Sri Lanka', '', 'LKR', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('29cca31b-4bad-4998-a56c-54e39b17a71d', 'LS', 'LSO', N'', 'Lesotho', '', 'LSL', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('fe0f9850-50b1-4f32-a326-e726d17f7a8e', 'LT', 'LTU', N'', 'Lithuania', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('0eb49530-c513-4d59-9f1d-8a0ebf5f8994', 'LU', 'LUX', N'', 'Luxembourg', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('64e32169-e17d-44f7-934b-fb073b58ce47', 'LV', 'LVA', N'', 'Latvia', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('58a08d45-849c-489d-85c1-ea4cc276f3e2', 'MO', 'MAC', N'', 'Macao', '', 'MOP', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('012a9a4f-ff4c-4e79-ac8e-bf0548f404c2', 'MF', 'MAF', N'', 'Saint Martin (French part)', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('cfd041f1-0067-4358-a327-e0ef7d32eaf5', 'MA', 'MAR', N'', 'Morocco', '', 'MAD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('01f4c80b-d576-4610-90cc-7501ae7d684b', 'MC', 'MCO', N'', 'Monaco', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('070ae1dd-02cd-4056-b443-27a42d53aae9', 'MD', 'MDA', N'', 'Moldova, Republic of', '', 'MDL', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('36a78de7-15ff-4798-a3c1-a6fdd31bd12e', 'MG', 'MDG', N'', 'Madagascar', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('576f9da6-b84b-4ad4-a726-1ea68e8f9358', 'MV', 'MDV', N'', 'Maldives', '', 'MVR', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('84cb572b-358c-4981-94eb-5862baaa3db4', 'MX', 'MEX', N'', 'Mexico', '', 'MXN', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('c5051232-a695-4e77-978b-15b4027e03b9', 'MH', 'MHL', N'', 'Marshall Islands', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('ef0e1570-1dff-4566-b7d7-3e0462988b7a', 'MK', 'MKD', N'', 'North Macedonia', '', 'MKD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('fa4742f1-e952-437e-914e-30e2a66ea739', 'ML', 'MLI', N'', 'Mali', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('4687bd62-8d84-419b-abc8-d56df10ab9f3', 'MT', 'MLT', N'', 'Malta', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('d5987ee4-d7fb-4953-8c28-012ac1b0816f', 'MM', 'MMR', N'', 'Myanmar', '', 'MMK', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('8be80c35-3e18-4b85-887b-e058b084751a', 'ME', 'MNE', N'', 'Montenegro', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('60a9ae5d-5e75-4f81-8e56-516dea54aa7f', 'MN', 'MNG', N'', 'Mongolia', '', 'MNT', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('bbb56cdc-4678-46e1-bbf8-2a0e184f459c', 'MP', 'MNP', N'', 'Northern Mariana Islands', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('b82dae86-4240-484d-8ca5-7a955fb64bb7', 'MZ', 'MOZ', N'', 'Mozambique', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('b695f2f9-3b2c-4a3f-b7dc-816bfa9db91a', 'MR', 'MRT', N'', 'Mauritania', '', 'MRO', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('754af6c1-3740-40e3-b229-4b391f7d1681', 'MS', 'MSR', N'', 'Montserrat', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('136f5286-0606-43b9-9148-1a18581003f9', 'MQ', 'MTQ', N'', 'Martinique', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('78f035ab-bcc9-45b1-8382-77c624f704a1', 'MU', 'MUS', N'', 'Mauritius', '', 'MUR', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('e7fcdad4-6794-4f87-86cc-3a21aa05dd4b', 'MW', 'MWI', N'', 'Malawi', '', 'MWK', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('f86708f5-b694-49a7-b3b3-828eab0afe1f', 'MY', 'MYS', N'', 'Malaysia', '', 'MYR', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('f5450b08-d26a-49d4-a1a1-0e9733f60778', 'YT', 'MYT', N'', 'Mayotte', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('8d4389b9-03fd-4a7e-ae6d-5c725b36b8b6', 'NA', 'NAM', N'', 'Namibia', '', 'NAD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('f42d2fc4-e76e-436e-80c4-6bd4f91d78f2', 'NC', 'NCL', N'', 'New Caledonia', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('4658b91d-2d73-4f93-87b3-1fc8c2374db9', 'NE', 'NER', N'', 'Niger', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('795a5f98-94a2-4ff9-b962-cdd1bd3b586e', 'NF', 'NFK', N'', 'Norfolk Island', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('d74d51f9-89b0-422a-8947-39f754327b45', 'NG', 'NGA', N'', 'Nigeria', '', 'NGN', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('82414c81-f946-4c05-9df7-c8f4c3b7f8e9', 'NI', 'NIC', N'', 'Nicaragua', '', 'NIO', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('22df3b53-c559-420f-b52c-9db17f523b0c', 'NU', 'NIU', N'', 'Niue', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('67e20c8f-04e5-41d3-8e98-1bab7c155692', 'NL', 'NLD', N'', 'Netherlands', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('67e8ef3d-84ea-499d-9c9f-8b2b3151fc57', 'NO', 'NOR', N'', 'Norway', '', 'NOK', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('c2870bb4-ff95-4560-8a48-dc626dc19699', 'NP', 'NPL', N'', 'Nepal', '', 'NPR', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('8c92024d-9b50-4224-8c4d-6816d41df74f', 'NR', 'NRU', N'', 'Nauru', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('56b602ec-a336-4691-aac6-38efe4f91f77', 'NZ', 'NZL', N'', 'New Zealand', '', 'NZD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('98c8042a-c995-4c75-8a47-74a9f7a20ead', 'OM', 'OMN', N'', 'Oman', '', 'OMR', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('5878ef9e-d9d0-4e64-8a01-65898226e8a3', 'PK', 'PAK', N'', 'Pakistan', '', 'PKR', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('4e33c2f7-9540-4d31-9347-ff9c135ec249', 'PA', 'PAN', N'', 'Panama', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('ac0a795c-8a6a-4437-8909-348287bb9f1a', 'PN', 'PCN', N'', 'Pitcairn', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('2b097e2b-d0b5-48c1-8cde-2b4b8f99815f', 'PE', 'PER', N'', 'Peru', '', 'PEN', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('a73fcaca-63aa-427c-899e-6ede442bb59d', 'PH', 'PHL', N'', 'Philippines', '', 'PHP', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('3d4a0262-7056-4fa9-b6e7-2f632c0cc69e', 'PW', 'PLW', N'', 'Palau', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('dd82b34f-8444-4746-8af1-faf9e546deb1', 'PG', 'PNG', N'', 'Papua New Guinea', '', 'PGK', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('95d55d3a-23c6-4293-afad-09e6677c51d1', 'PL', 'POL', N'', 'Poland', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('7bf1750b-c8f0-42b9-9305-bffa1576d0c0', 'PR', 'PRI', N'', 'Puerto Rico', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('5e891590-2a09-4a0f-b12a-732a7da2cb99', 'KP', 'PRK', N'', 'Korea, Democratic People''s Republic of', '', 'KPW', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('c73703d1-fb69-472a-8d96-59ee2e1e7e11', 'PT', 'PRT', N'', 'Portugal', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('60a3ee5d-34d8-49bf-bc8f-7969d850ac0b', 'PY', 'PRY', N'', 'Paraguay', '', 'PYG', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('78765c8e-857c-48f0-a945-4438ef84b91d', 'PS', 'PSE', N'', 'Palestine, State of', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('02beddaa-a4f6-4549-af1c-9b311cf0e389', 'PF', 'PYF', N'', 'French Polynesia', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('b9a41256-e692-4abd-a4ec-b3d2e5d18be7', 'QA', 'QAT', N'', 'Qatar', '', 'QAR', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('1267d210-2658-44aa-8b47-e8799b04a054', 'RE', 'REU', N'', 'Réunion', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('90f81210-5683-4c49-9d35-c92c0902528a', 'RO', 'ROU', N'', 'Romania', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('64d4dbca-811e-4086-97e2-3fc52ba709e1', 'RU', 'RUS', N'', 'Russian Federation', '', 'RUB', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('2ee10d52-2112-444a-835e-7951add784ee', 'RW', 'RWA', N'', 'Rwanda', '', 'RWF', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('286626ad-a374-4248-84d4-988657ba0704', 'SA', 'SAU', N'', 'Saudi Arabia', '', 'SAR', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('c2f230da-532c-4e54-a3f1-3aa92cb9f071', 'SD', 'SDN', N'', 'Sudan', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('cfb4ef56-a7fb-404c-9c49-6d0dabf1bf75', 'SN', 'SEN', N'', 'Senegal', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('c60d04d8-7c61-48cd-ad8e-114b3292ec2f', 'SG', 'SGP', N'', 'Singapore', '', 'SGD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('68032a15-ccc3-45fe-9ad0-ba40a16cf5a1', 'GS', 'SGS', N'', 'South Georgia and the South Sandwich Islands', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('3916046a-b630-40b5-a77a-41f67ccc7d03', 'SH', 'SHN', N'', 'Saint Helena, Ascension and Tristan da Cunha', '', 'SHP', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('0a108fc2-7eda-452f-b66b-60dca4fff1f5', 'SJ', 'SJM', N'', 'Svalbard and Jan Mayen', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('75125520-7b76-4920-99a2-3625f073a56a', 'SB', 'SLB', N'', 'Solomon Islands', '', 'SBD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('2584781f-1140-4605-98c9-afc165860b30', 'SL', 'SLE', N'', 'Sierra Leone', '', 'SLL', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('d9637021-6901-46ec-b60f-119ee9852d0f', 'SV', 'SLV', N'', 'El Salvador', '', 'SVC', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('e5bfa090-b9b0-433c-928b-8ee3f8843de1', 'SM', 'SMR', N'', 'San Marino', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('e78a756d-e6ca-4a2e-8a3a-944fcdfff321', 'SO', 'SOM', N'', 'Somalia', '', 'SOS', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('32175163-716a-49db-9ed1-a9e891a0ba96', 'PM', 'SPM', N'', 'Saint Pierre and Miquelon', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('dc5003d6-5252-4095-8bc8-dcde1d512abc', 'RS', 'SRB', N'', 'Serbia', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('b02ecf9c-190e-4154-95f0-b52fb69de79e', 'SS', 'SSD', N'', 'South Sudan', '', 'SSP', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('beac215b-61c0-491f-880f-cd0c492f3cde', 'ST', 'STP', N'', 'Sao Tome and Principe', '', 'STD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('bc5502d8-cdd0-4f6d-94ab-de64bec46b91', 'SR', 'SUR', N'', 'Suriname', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('36aa06ce-fead-42be-a289-ea24c8b5cd19', 'SK', 'SVK', N'', 'Slovakia', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('a2f47096-3edf-48cb-b16e-1829c204e5a6', 'SI', 'SVN', N'', 'Slovenia', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('1b0ed8a9-73b5-4763-ba56-370768ff693b', 'SE', 'SWE', N'', 'Sweden', '', 'SEK', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('6f65ece0-c7bf-43e5-bc4f-d763965816ed', 'SZ', 'SWZ', N'', 'Eswatini', '', 'SZL', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('af4d9552-778d-4124-9fa5-15d25c32e129', 'SX', 'SXM', N'', 'Sint Maarten (Dutch part)', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('9ea353b2-5347-4b51-a92a-9ff16e23a161', 'SC', 'SYC', N'', 'Seychelles', '', 'SCR', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('22f875a0-2f55-4424-8f54-d8d5221e8384', 'SY', 'SYR', N'', 'Syrian Arab Republic', '', 'SYP', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('4e4e4f0d-0866-49f0-ba33-64950c980041', 'TC', 'TCA', N'', 'Turks and Caicos Islands', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('fcd82417-8390-428b-b291-1922fbb0b326', 'TD', 'TCD', N'', 'Chad', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('651a3819-aa9a-4c32-9488-8102757085be', 'TG', 'TGO', N'', 'Togo', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('d2e1490b-0b2d-460b-9dd0-b8396717fc4f', 'TH', 'THA', N'', 'Thailand', '', 'THB', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('580f40cb-dccf-4377-b6fc-85a48827c093', 'TJ', 'TJK', N'', 'Tajikistan', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('4eb15a14-4683-4cd4-89c0-3deefa08802d', 'TK', 'TKL', N'', 'Tokelau', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('f31104d8-d55b-406a-8cdc-93615df4b7b9', 'TM', 'TKM', N'', 'Turkmenistan', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('feb12816-e0b3-4c43-87f4-04720f706c18', 'TL', 'TLS', N'', 'Timor-Leste', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('0f62a721-b58b-474f-bcfa-65b1c4a6c319', 'TO', 'TON', N'', 'Tonga', '', 'TOP', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('bc87f3d9-979c-4f45-ad25-52ff04b9aa97', 'TT', 'TTO', N'', 'Trinidad and Tobago', '', 'TTD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('fc7eec13-9a78-45e9-92aa-22f7167975b2', 'TN', 'TUN', N'', 'Tunisia', '', 'TND', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('bc0b6c6d-d597-4339-892a-914db9e49fae', 'TR', 'TUR', N'', 'Turkey', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('48e3b337-1e28-4859-8954-d1b9f5261ab6', 'TV', 'TUV', N'', 'Tuvalu', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('1c9fd78b-e715-4dfa-89fd-f0418a1fec20', 'TW', 'TWN', N'', 'Taiwan, Province of China', '+886', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('d4a8f751-e67e-4279-b3a8-b6f29b9ad407', 'TZ', 'TZA', N'', 'Tanzania, United Republic of', '', 'TZS', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('c6828828-dade-4bdc-bd0e-f5d264a5c6ca', 'UG', 'UGA', N'', 'Uganda', '', 'UGX', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('5339277f-c9f5-4a91-a8cb-14682158cbc5', 'UA', 'UKR', N'', 'Ukraine', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('42c9dd7d-2606-4590-bce4-60ff73c61036', 'UM', 'UMI', N'', 'United States Minor Outlying Islands', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('924f7031-36f5-48df-9b2b-ee96384d30e5', 'UY', 'URY', N'', 'Uruguay', '', 'UYU', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('c9077490-6b36-4a62-89ce-8ff50a977b5c', 'US', 'USA', N'', 'United States', '+1', 'USD', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('b2baf6c1-aecb-4f0a-9e18-724c7a38e435', 'UZ', 'UZB', N'', 'Uzbekistan', '', 'UZS', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('fc46042e-fa4d-4fde-8290-935c8e0c4c8a', 'VA', 'VAT', N'', 'Holy See (Vatican City State)', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('c2c4b847-8e2b-4594-b02e-1923b2493175', 'VC', 'VCT', N'', 'Saint Vincent and the Grenadines', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('87ee1b3a-938b-4847-9e55-1125bf0ddf62', 'VE', 'VEN', N'', 'Venezuela, Bolivarian Republic of', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('a17edcb9-b2b4-4ed7-8196-db2c8eb8b95d', 'VG', 'VGB', N'', 'Virgin Islands, British', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('7d01d954-3077-4790-ae9b-e5fc38c30fa3', 'VI', 'VIR', N'', 'Virgin Islands, U.S.', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('9c106ba0-ea55-4ef8-85a3-5c7c6536e67a', 'VN', 'VNM', N'', 'Viet Nam', '', 'VND', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('1a2336a9-a069-4fb5-9bee-78f323d585cf', 'VU', 'VUT', N'', 'Vanuatu', '', 'VUV', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('23e7b3b3-16a8-4c97-a11a-3c69e9d0d54b', 'WF', 'WLF', N'', 'Wallis and Futuna', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('606d9cbc-59be-495d-b69a-618b7b9536a0', 'WS', 'WSM', N'', 'Samoa', '', 'WST', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('8d709bea-beec-4ffa-b3cd-b09ddc3c445d', 'YE', 'YEM', N'', 'Yemen', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('6baebfd8-c33a-4294-bf94-225feab334fe', 'ZA', 'ZAF', N'', 'South Africa', '', 'ZAR', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('85b10d96-f7c4-40ed-86f8-bc273c8127bc', 'ZM', 'ZMB', N'', 'Zambia', '', '', 1);
INSERT INTO [dbo].[sdb0country] (country_id, iso_code, iso3_code, country_name_zh, country_name_en, phone_code, currency_code, is_active) VALUES ('1e5a7292-1551-4724-9549-f65463ba2062', 'ZW', 'ZWE', N'', 'Zimbabwe', '', '', 1);