-- 建立 AG
CREATE AVAILABILITY GROUP [AG_DevGroup]
WITH (
    AUTOMATED_BACKUP_PREFERENCE = PRIMARY,
    FAILURE_CONDITION_LEVEL = 3,
    HEALTH_CHECK_TIMEOUT = 60000
)
FOR REPLICA ON
    N'mssql-primary' WITH (
        ENDPOINT_URL = 'tcp://192.168.25.101:5022',
        AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
        FAILOVER_MODE = AUTOMATIC,
        SEEDING_MODE = AUTOMATIC
    ),
    N'mssql-secondary1' WITH (
        ENDPOINT_URL = 'tcp://192.168.25.102:5022',
        AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
        FAILOVER_MODE = AUTOMATIC,
        SEEDING_MODE = AUTOMATIC
    ),
    N'mssql-secondary2' WITH (
        ENDPOINT_URL = 'tcp://192.168.25.103:5022',
        AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT,
        FAILOVER_MODE = MANUAL,
        SEEDING_MODE = AUTOMATIC
    );

-- 設定 Listener 虛擬 IP + 名稱
ALTER AVAILABILITY GROUP [AG_DevGroup]
ADD LISTENER 'AGListener'
(
    WITH IP ((N'192.168.25.250', N'255.255.255.0')),
    PORT = 1433
);

-- 加入資料庫
ALTER AVAILABILITY GROUP [AG_DevGroup] ADD DATABASE [TestDB];
